baseurl = "https://scorpil.com/"
title = "Software Development Blog"
freelance ="Freelance"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Andrew Savchyn"
disqusShortname = "Scorpil"

[Privacy]

[Privacy.disqus]
    disable = false

[Author]
    name = "Scorpil"
    profile = "https://twitter.com/scorpil"

[Taxonomies]
    tag = "tags"

[Params]
    headline = "Distributed Systems / Cloud Computing / AI"
    metaDescription = "Blog about Software Development, Distributed Systems, Cloud Computing, Artificial Intelligence, and other related topics."
    intro = true

    github = "https://github.com/scorpil"
    gitlab = "https://gitlab.com/scorpil"
    linkedin = "https://linkedin.com/in/asavchyn/"
    twitter = "https://twitter.com/scorpil"
    mastodon = "https://mastodon.social/@scorpil"
    stackoverflow = "https://stackoverflow.com/users/186518/scorpil"
    email = "dev@scorpil.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = false
    readingTimeText = "Estimating reading time: "

[Permalinks]
    post = "/post/:filename/"

[markup.goldmark.renderer]
    unsafe = true

#[[menu.main]]
#    name = "Freelance"
#    url = "/freelance/"
#    weight = 1
